"""ZhiYao-Graph project configuration — fixed-data pipeline version.

Data-stage rule
---------------
All final experiments must read immutable files generated by
``scripts/prepare_final_datasets.py`` under ``data_final``.
Training/evaluation code must not sample, re-split, or fit scalers itself.

Model architecture values are intentionally kept at the current project values
during the data-fix stage. Architecture changes are handled later.
"""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent

# ---------------------------------------------------------------------
# Data paths
# ---------------------------------------------------------------------
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
BATCHDTA_SOURCE_DIR = (
    PROJECT_ROOT / "data" / "colab" / "BatchDTA_processed_data"
)
FINAL_DATA_DIR = PROJECT_ROOT / "data_final"
MODEL_DIR = PROJECT_ROOT / "checkpoints"
EVALUATION_OUTPUT_DIR = PROJECT_ROOT / "evaluation_outputs"
TRAINING_OUTPUT_DIR = PROJECT_ROOT / "training_outputs"

# Temporary legacy aliases. New code should use the explicit names above.
DATA_DIR = str(RAW_DATA_DIR)
PROCESSED_DIR = str(FINAL_DATA_DIR)

DATA_CONFIG = {
    "datasets": ["KIBA", "DAVIS"],
    "settings": ["warm", "cold_drug", "cold_target"],
    "source_root": str(BATCHDTA_SOURCE_DIR),
    "final_root": str(FINAL_DATA_DIR),

    # These seeds are used only when scripts/prepare_final_datasets.py creates
    # the immutable split files. Model seeds are separate.
    "warm_split_seed": 42,
    "cold_target_split_seed": 42,
    "cold_drug_split_seed": 42,
    "warm_ratios": [0.8, 0.1, 0.1],
    "cold_drug_ratios": [0.8, 0.1, 0.1],
    "cold_val_protein_fraction": 0.10,

    # All cleaned usable interactions are retained.
    "subsample_limit": None,

    # Benchmark-full main policy: retain repeated identical model inputs, but
    # force each input group into one split so no identical input crosses
    # train/val/test. Median/mean aggregation is reserved for sensitivity runs.
    "same_input_policy": "keep_grouped",

    # Labels are normalized using training labels only, separately per setting.
    "scaler": "train_only_minmax",
}

# Raw DeepDTA source URLs are kept only for source/reference retrieval.
# They are NOT the direct final training input of the current pipeline.
DATASET_CONFIG = {
    "kiba": {
        "url": "https://raw.githubusercontent.com/hkmztrk/DeepDTA/master/data/KIBA/",
        "drug_file": "drugs.txt",
        "target_file": "targets.txt",
        "affinity_file": "Y.txt",
        "role": "raw_reference_only",
    },
    "davis": {
        "url": "https://raw.githubusercontent.com/hkmztrk/DeepDTA/master/data/davis/",
        "drug_file": "drugs.txt",
        "target_file": "targets.txt",
        "affinity_file": "Y.txt",
        "role": "raw_reference_only",
    },
}

# ---------------------------------------------------------------------
# Molecular graph features
# ---------------------------------------------------------------------
ATOM_FEATURES = {
    "atom_type": [
        "C", "N", "O", "S", "F", "P", "Cl", "Br", "I", "B", "Si", "Se",
        "other",
    ],
    "degree": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "formal_charge": [-3, -2, -1, 0, 1, 2, 3],
    "num_hs": [0, 1, 2, 3, 4],
    "hybridization": [1, 2, 3],
}

BOND_FEATURES = {
    "bond_type": [1, 2, 3, 12],
    "stereo": [0, 1, 2, 3],
    "conjugated": [False, True],
    "in_ring": [False, True],
}

# ---------------------------------------------------------------------
# Canonical V3 model configuration
MODEL_ARCHITECTURE_VERSION = "zhiy_graph_v3_token_cross_attention"
# V1C pre-formal protocol identifier. This is intentionally a pre-formal
# version; bump it again only when all Pre-Formal gates pass and the new
# AdamW formal protocol is frozen.
PROTOCOL_VERSION = "zhiy_graph_adamw_formal_v1"
# ---------------------------------------------------------------------
DRUG_ENCODER = {
    "node_dim": 41,
    "edge_dim": 10,
    "hidden_dim": 128,
    "num_layers": 3,
    "dropout": 0.2,
    "encoder_type": "gat",
    "gat_heads": 4,
    "pooling": "add",  # preserve historical pooling; mean is a later sensitivity check
}

PROTEIN_ENCODER = {
    # PAD=0, 20 standard amino acids=1..20, X/unknown=21.
    "vocab_size": 22,
    "padding_idx": 0,
    "unk_idx": 21,
    "embed_dim": 128,
    "kernel_sizes": [3, 5, 7],
    "num_filters": 64,
    "hidden_dim": 128,
    "post_pool_layers": 1,
    "dropout": 0.2,
    # 1500 reduces truncation from ~20-26% of records at 1000 aa to ~2-4%.
    # A later sensitivity analysis should compare sequence-length choices.
    "max_len": 1500,
    "truncation": "right",
    "encoder_type": "cnn",
    "transformer_heads": 4,
    "transformer_layers": 2,
}

FUSION = {
    "drug_dim": 128,
    "protein_dim": 128,
    "hidden_dim": 256,
    # Product uses 128D element-wise alignment. Attention uses a separate
    # 80D internal space so all three fusion modules are within ~3% parameters.
    "align_dim": 128,
    "attention_align_dim": 80,
    "fusion_mode": "attention",
    "num_heads": 4,
    "dropout": 0.2,
}

PREDICTOR = {
    "input_dim": 256,
    "hidden_dims": [512, 256, 128],
    "output_dim": 1,
    "dropout": 0.3,
    "task": "regression",
    "normalization": "layernorm",
}

# ---------------------------------------------------------------------
# Training configuration
# ---------------------------------------------------------------------
TRAINING = {
    "optimizer": "adamw",
    "batch_size": 64,
    "learning_rate": 0.001,
    "weight_decay": 1e-5,
    "num_epochs": 200,
    "early_stopping_patience": 30,
    "early_stopping_min_delta": 0.0,
    "gradient_clip_norm": 5.0,
    "scheduler": "reduce_on_plateau",
    "scheduler_factor": 0.5,
    "scheduler_patience": 10,
    "scheduler_min_lr": 1e-6,
    "deterministic": True,
    "cudnn_benchmark": False,

    # Split ratios are intentionally NOT present here. Splits are immutable
    # data artifacts created before training. The same model seeds are paired
    # across fusion strategies for fair run-to-run comparisons.
    "seed": 42,
    "model_seeds": [42, 123, 2026],
    "extended_model_seeds": [42, 123, 2026, 3407, 7777],
    "device": "auto",
}

EVALUATION = {
    "metric_schema_version": "zhiy_graph_regression_metrics_v2",
    "primary_level": "record",
    "sensitivity_level": "unique_input",
    "test_policy": "sealed_until_explicit_evaluation_phase",
}

EXPERIMENT_MATRIX = {
    "datasets": ["KIBA", "DAVIS"],
    "settings": list(DATA_CONFIG["settings"]),
    "fusions": ["concat", "product", "attention"],
    "model_seeds": [42, 123, 2026],
}


# ---------------------------------------------------------------------
# Fifth-stage controlled reference baselines
# ---------------------------------------------------------------------
# These are self-contained, split-matched reimplementations for comparison
# under exactly the same fixed KIBA/DAVIS train/val/test files. They are
# intentionally named "*-style" because they are controlled reimplementations,
# not claims of bit-for-bit reproduction of published repositories.
BASELINES = {
    "deepdta_style": {
        "architecture_version": "deepdta_style_controlled_v1",
        "input_modality": "smiles_sequence+protein_sequence",
        "max_smiles_len": 200,
        "max_protein_len": 1500,
        "smiles_vocab": "fixed_printable_ascii",
        "smiles_embed_dim": 64,
        "protein_vocab_size": 22,
        "protein_embed_dim": 128,
        "conv_channels": [32, 64, 96],
        "kernel_sizes": [3, 5, 7],
        "encoder_output_dim": 128,
        "predictor_hidden_dims": [512, 256],
        "dropout": 0.2,
        "description": (
            "DeepDTA-style controlled baseline: character-level canonical-SMILES "
            "CNN + protein-sequence CNN + concatenation regression head."
        ),
    },
    "graphdta_gcn_style": {
        "architecture_version": "graphdta_gcn_style_controlled_v1",
        "input_modality": "molecular_graph+protein_sequence",
        "max_protein_len": 1500,
        "node_dim": 41,
        "gcn_hidden_dim": 128,
        "gcn_layers": 3,
        "graph_pooling": "max",
        "protein_vocab_size": 22,
        "protein_embed_dim": 128,
        "conv_channels": [32, 64, 96],
        "kernel_sizes": [3, 5, 7],
        "encoder_output_dim": 128,
        "predictor_hidden_dims": [512, 256],
        "dropout": 0.2,
        "description": (
            "GraphDTA-GCN-style controlled baseline: GCN molecular graph encoder "
            "+ protein-sequence CNN + concatenation regression head."
        ),
    },
}

BASELINE_EXPERIMENT_MATRIX = {
    "datasets": ["KIBA", "DAVIS"],
    "settings": list(DATA_CONFIG["settings"]),
    "baselines": ["deepdta_style", "graphdta_gcn_style"],
    "model_seeds": [42, 123, 2026],
}

# ---------------------------------------------------------------------
# Fifth-stage prespecified sensitivity experiments
# ---------------------------------------------------------------------
# The primary V3 matrix remains unchanged (1500-aa proteins, add pooling).
# Sensitivity runs modify ONE factor at a time while keeping the neutral
# ConcatFusion condition fixed, so the sensitivity experiment isolates the
# encoder/preprocessing factor instead of conflating it with fusion choice.
SENSITIVITY_EXPERIMENTS = {
    "protein_len_1000": {
        "description": "Protein max_len 1000 versus primary 1500-aa protocol",
        "fusion": "concat",
        "overrides": {
            "protein_max_len": 1000,
            "drug_pooling": "add",
        },
        "reference": {
            "experiment": "primary",
            "fusion": "concat",
            "protein_max_len": 1500,
            "drug_pooling": "add",
        },
    },
    "drug_pool_mean": {
        "description": "Graph global mean pooling versus primary global add pooling",
        "fusion": "concat",
        "overrides": {
            "protein_max_len": 1500,
            "drug_pooling": "mean",
        },
        "reference": {
            "experiment": "primary",
            "fusion": "concat",
            "protein_max_len": 1500,
            "drug_pooling": "add",
        },
    },
}

SENSITIVITY_EXPERIMENT_MATRIX = {
    "datasets": ["KIBA", "DAVIS"],
    "settings": list(DATA_CONFIG["settings"]),
    "variants": ["protein_len_1000", "drug_pool_mean"],
    "model_seeds": [42, 123, 2026],
}

# Efficiency is measured only on validation data so runtime benchmarking never
# becomes another route by which held-out test information enters development.
EFFICIENCY_BENCHMARK = {
    "split": "val",
    "warmup_batches": 5,
    "measure_batches": 20,
    "batch_size": 64,
    "representative_seed": 42,
    "report": [
        "trainable_parameters",
        "checkpoint_bytes",
        "mean_batch_latency_ms",
        "median_batch_latency_ms",
        "p95_batch_latency_ms",
        "throughput_samples_per_second",
        "cuda_peak_memory_bytes",
    ],
}

EXTENDED_EXPERIMENT_COUNTS = {
    "primary_fusion_runs": (
        len(EXPERIMENT_MATRIX["datasets"])
        * len(EXPERIMENT_MATRIX["settings"])
        * len(EXPERIMENT_MATRIX["fusions"])
        * len(EXPERIMENT_MATRIX["model_seeds"])
    ),
    "controlled_baseline_runs": (
        len(BASELINE_EXPERIMENT_MATRIX["datasets"])
        * len(BASELINE_EXPERIMENT_MATRIX["settings"])
        * len(BASELINE_EXPERIMENT_MATRIX["baselines"])
        * len(BASELINE_EXPERIMENT_MATRIX["model_seeds"])
    ),
    "sensitivity_runs": (
        len(SENSITIVITY_EXPERIMENT_MATRIX["datasets"])
        * len(SENSITIVITY_EXPERIMENT_MATRIX["settings"])
        * len(SENSITIVITY_EXPERIMENT_MATRIX["variants"])
        * len(SENSITIVITY_EXPERIMENT_MATRIX["model_seeds"])
    ),
}
EXTENDED_EXPERIMENT_COUNTS["total_prespecified_training_runs"] = (
    EXTENDED_EXPERIMENT_COUNTS["primary_fusion_runs"]
    + EXTENDED_EXPERIMENT_COUNTS["controlled_baseline_runs"]
    + EXTENDED_EXPERIMENT_COUNTS["sensitivity_runs"]
)
